### ISSUE TITLE
Website refresh post-merge task list

### ISSUE THREAD

**Issue by SgtCoDFish** [cert-manager/website#891]
## Tasks remaining

- [x] Ensure that the build script `./scripts/build-release` works for the refreshed website
- [x] Ensure that the API / CLI doc generation is happening and working for the refreshed website
- [ ] Ensure the version picker is working
- [ ] Check links on all docs versions
- [x] Fix comments: https://deploy-preview-896--cert-manager-website.netlify.app/docs/installation/supported-releases/ 
- [x] Underlining on "Documentation" in title bar
- [ ] Check that public key download links work on [Code signing page](https://deploy-preview-896--cert-manager-website.netlify.app/docs/installation/code-signing/)
- [ ] [API reference](https://deploy-preview-896--cert-manager-website.netlify.app/docs/reference/api-docs/) is hard to read due to missing table borders.
- [x] #942
- [ ] Key usage looks silly on [api docs](https://deploy-preview-896--cert-manager-website.netlify.app/docs/reference/api-docs/)
- [ ] Check `<title>`s across the site for correctness
- [x] README + anchors bug fix (see below)
- [ ] Going up bug fix (see below)
- [ ] https://cert-manager.io/docs/configuration/ - fix supported issuer types list
- [ ] Check other places for auto-generated hugo lists which are missing
- [ ] Version selector could be clearer
- [ ] Update README at root of repo
- [ ] Trailing slashes on links (fixing `htmltest`)
- [ ] Fix links for downloading YAML, e.g.  `https://cert-manager.io/docs/tutorials/acme/example/deployment.yaml` from the nginx-ingress tutorial

### Bug from 2022-04-12: Going up

:bug: Bug raised upstream, see https://github.com/zentered/next-product-docs/issues/4

Another bug is that I can't go "up" past the docs version. E.g. on the v1.8-docs, on [this page](https://deploy-preview-896--cert-manager-website.netlify.app/v1.8-docs/installation/helm/)

I want `Install a supported version of Kubernetes or OpenShift` to link to `/docs/installation/supported-releases.md`.  `supported-releases.md` doesn't exist on anything except `/docs`.

But none of the expected links work:

* `../../../docs/installation/supported-releases.md`ends up linking to `/v1.8-docs/installation/installation/supported-releases/`
* So does `../../docs/installation/supported-releases.md` and `../../../../docs/installation/supported-releases.md`
* So does `/docs/installation/supported-releases.md`

It doesn't actually seem possible to link to a different docs version in any case

### Fixed: README + anchors

To reproduce:

1. I go to https://deploy-preview-896--cert-manager-website.netlify.app/docs/contributing/policy/#sign-certificates-using-the-kubernetes-ca-used-for-your-nodes
2. Click "see our FAQ"
3. This redirects to https://deploy-preview-896--cert-manager-website.netlify.app/docs/faq/readme/#kubernetes-has-a-builtin-certificatesigningrequest-api-why-not-use-that (note /readme at the end)
4. Relative links are broken, e.g. at the top of the page the link titled "the renew command's page" is now broken but it works on the [page without the readme suffix](https://deploy-preview-896--cert-manager-website.netlify.app/docs/faq/)

## Before final deployment

These steps are taken before we merge for real. This will get `next-website` into a state where it can be merged into `master`.

Prep:

1. Ensure that website@`next-website-base` is fully up to date. Should include all commits from `next-website` except the last one (which adds the docs)
2. Warn people of a change freeze to the website for a few hours. No new PRs merged during the freeze.

Updating:

1. Locally, pull the latest changes from website@master and [rutte](https://github.com/SgtCoDFish/rutte)@main
2. Checkout master on the website repo.
3. Edit the rutte makefile at the path where the website is checked out
4. Run `./scripts/gendocs/generate`  on the website repo
5. Run `make cleancheckout` in the rutte repo.
6. Check out website@`next-website`

7. In the website dir: `git rebase -i master` and edit the `add auto-converted docs` commit
8.  You'll have to fix rebasing for the first commit, amend that, `git rebase --continue`
9. From the rutte dir: `cp -r content-out/* ~/workspace/cert-manager-website/content/`
10. In the website, `git commit --amend -a`, `git rebase --continue`
11. On the "update build scripts" commit, uncomment all API docs generation and rebuild all with `./scripts/gendocs/generate`
12. Amend commit if anything changed
13. Consider amending the commits if needed, for a smoother merge (e.g. combine the content commit you just amended with the first PR which deletes all `content/en`. Might make git pick up the renames and preserve history)

**Comment by SgtCoDFish** [comment]
Most of this was done, but wasn't necc. tracked as it was done. I don't think this issue is providing any value any more so I'll close.
